sudo: true
dist: trusty
language: python
python:
  - "3.5"
services:
  - docker
cache:
  - $HOME/ccache
jobs:
  include:
   - stage: Building preCICE with ccache
     name: "Ubuntu 18.04.package"
     if: fork = false
     script:
     - source setup_ccache_sync.sh
     - docker build --build-arg CCACHE_REMOTE=$CCACHE_REMOTE -f Dockerfile.Ubuntu1804.package -t precice .
