sudo: true
dist: trusty
language: python
python:
  - "3.5"
services:
  - docker
jobs:
  include:
  - stage: Building preCICE
    name: "Ubuntu 16.04"
    script:
    - docker build -f Dockerfile.Ubuntu1604 -t precice .
    after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker images
    - docker tag precice $DOCKER_USERNAME/precice-ubuntu1604-develop:latest
    - docker push $DOCKER_USERNAME/precice-ubuntu1604-develop:latest

  - stage: Building preCICE
    name: "Ubuntu 18.04"
    script:
    - docker build -f Dockerfile.Ubuntu1804 -t precice .
    after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker images
    - docker tag precice $DOCKER_USERNAME/precice-ubuntu1804-develop:latest
    - docker push $DOCKER_USERNAME/precice-ubuntu1804-develop:latest

  - stage: System Tests
    script:
    - python system_testing.py -s su2-ccx
    name: "[16.04] SU2 <-> Calculix"
    after_success:
    - python push.py -s -t su2-ccx
    after_failure:
    - python push.py -t su2-ccx
  - script:
    - python system_testing.py -s of-of
    name: "[16.04] OpenFOAM <-> OpenFOAM"
    after_success:
    - python push.py -s -t of-of
    after_failure:
    - python push.py -t of-of
  - script:
    - python system_testing.py -s of-ccx
    name: "[16.04] Calculix <-> OpenFOAM"
    after_success:
    - python push.py -s -t of-ccx
    after_failure:
    - python push.py -t of-ccx
  - script:
    - python system_testing.py -s bindings
    name: "[16.04] Python bindings"
    after_success:
    - python push.py -s -t bindings
    after_failure:
    - python push.py -t bindings


  - script:
    - python system_testing.py -s su2-ccx -o Ubuntu1804
    name: "[18.04] SU2 <-> Calculix"
    after_success:
    - python push.py -s -t su2-ccx -o Ubuntu1804
    after_failure:
    - python push.py -t su2-ccx -o Ubuntu1804
  - script:
    - python system_testing.py -s of-of -o Ubuntu1804
    name: "[18.04] OpenFOAM <-> OpenFOAM"
    after_success:
    - python push.py -s -t of-of -o Ubuntu1804
    after_failure:
    - python push.py -t of-of -o Ubuntu1804
  - script:
    - python system_testing.py -s of-ccx -o Ubuntu1804
    name: "[18.04] Calculix <-> OpenFOAM"
    after_success:
    - python push.py -s -t of-ccx -o Ubuntu1804
    after_failure:
    - python push.py -t of-ccx -o Ubuntu1804
  - script:
    - python system_testing.py -s bindings -o Ubuntu1804
    name: "[18.04] Python bindings"
    after_success:
    - python push.py -s -t bindings -o Ubuntu1804
    after_failure:
    - python push.py -t bindings -o Ubuntu1804

